# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default title', max_length=10)),
                ('name', models.TextField(default='default name')),
                ('when', models.TextField(default='default when')),
                ('theme', models.TextField(default='default theme')),
                ('goods', models.TextField(default='default goods')),
                ('who', models.TextField(default='default who')),
                ('where', models.TextField(default='default where')),
                ('link', models.TextField(default='default link')),
                ('how', models.TextField(default='default how')),
                ('image', models.ImageField(default='default.png', upload_to='01')),
            ],
        ),
    ]
